# Generated by Django 5.2.8 on 2026-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bambu_run", "0003_cloud_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="filament",
            name="ams_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMS", "AMS"),
                    ("AMS 2 Pro", "AMS 2 Pro"),
                    ("AMS HT", "AMS HT"),
                ],
                default="",
                help_text="Type of the AMS unit this spool is loaded in (AMS / AMS 2 Pro / AMS HT)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="filament",
            name="ams_unit_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Which physical AMS unit this spool is loaded in (matches MQTT ams[i].id; 128 = AMS HT)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printermetrics",
            name="nozzle_diameter_left",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Left nozzle diameter (mm). H2C only.",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printermetrics",
            name="nozzle_target_temp_left",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Left extruder target temperature (°C). H2C only.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printermetrics",
            name="nozzle_temp_left",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Left extruder current temperature (°C). H2C only.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printermetrics",
            name="nozzle_type_left",
            field=models.CharField(
                blank=True,
                help_text="Left nozzle type (e.g. HS01-0.4). H2C only.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filament",
            name="current_tray_id",
            field=models.IntegerField(
                blank=True,
                help_text="Tray slot index within its AMS unit (0-3 for AMS/AMS 2 Pro, 0 for AMS HT)",
                null=True,
            ),
        ),
    ]
