# Generated by Django 5.2.8 on 2026-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bambu_run", "0004_h2c_dual_nozzle_and_ams_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="printermetrics",
            name="vortek_raw",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw print.device MQTT payload (Vortek rack groundwork)",
            ),
        ),
    ]
