# Generated by Django 5.2.8 on 2026-06-20 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bambu_run", "0006_alter_filamentsnapshot_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(db_index=True, max_length=100)),
                (
                    "nozzle_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "raw_id",
                    models.PositiveSmallIntegerField(
                        help_text="Last-seen MQTT device.nozzle.info[].id"
                    ),
                ),
                (
                    "slot_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rack bay 1-6, derived from raw_id 16-21. Null if currently unknown (e.g. mounted on toolhead and id reports as the 0 sentinel).",
                        null=True,
                    ),
                ),
                (
                    "is_toolhead",
                    models.BooleanField(
                        default=False,
                        help_text="True if currently mounted on the toolhead under normal polling (raw_id == 0).",
                    ),
                ),
                (
                    "last_filament_profile_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bambu material profile id of the filament last loaded (MQTT fila_id, e.g. 'GFA01')",
                        max_length=20,
                    ),
                ),
                (
                    "last_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="6-char hex of the filament last loaded (MQTT color_m, alpha stripped)",
                        max_length=6,
                    ),
                ),
                ("used_time_seconds", models.PositiveIntegerField(default=0)),
                (
                    "wear_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="MQTT wear (0-128 scale) converted to a 0-100 percent",
                        max_digits=5,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotends",
                        to="bambu_run.printer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotend",
                "verbose_name_plural": "Hotends",
                "db_table": "infrastructure_hotend",
                "ordering": ["printer", "-is_toolhead", "slot_number", "serial_number"],
                "unique_together": {("printer", "serial_number")},
            },
        ),
        migrations.CreateModel(
            name="HotendSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_id", models.PositiveSmallIntegerField()),
                ("used_time_seconds", models.PositiveIntegerField(default=0)),
                (
                    "wear_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "stat",
                    models.IntegerField(
                        blank=True,
                        help_text="Raw MQTT status code for this hotend",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "hotend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="bambu_run.hotend",
                    ),
                ),
                (
                    "printer_metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotend_snapshots",
                        to="bambu_run.printermetrics",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotend Snapshot",
                "verbose_name_plural": "Hotend Snapshots",
                "db_table": "infrastructure_hotend_snapshot",
                "ordering": ["printer_metric", "hotend"],
                "indexes": [
                    models.Index(
                        fields=["printer_metric", "hotend"],
                        name="infrastruct_printer_b528aa_idx",
                    ),
                    models.Index(
                        fields=["hotend", "-timestamp"],
                        name="infrastruct_hotend__691f7e_idx",
                    ),
                ],
            },
        ),
    ]
