# Generated by Django 5.2.8 on 2026-06-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bambu_run", "0007_hotend_hotendsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="printermetrics",
            name="nozzle_info",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Parsed per-poll nozzle/hotend info list",
            ),
        ),
    ]
